### ISSUE TITLE
Consider supporting nesting

### ISSUE THREAD

**Issue by benknight** [jotaen/xit#41]
I recently tried to convert my existing plaintext TODO list which uses Github's Markdown format for showing checkboxes, combined with indentation for nesting sub-items, for example:

```
- [x] Item 1
  - [x] Subitem 1
  - [ ] Subitem 2
```

Which is nicely rendered by Github:

- [x] Item 1
  - [x] Subitem 1
  - [ ] Subitem 2

I don't mind if [x]it! doesn't prioritize feature parity with Github Markdown checkboxes like the example, but it would be nice if nested lists were supported. Once I remove the hyphens, here's how this list gets formatted in VSCode using the xit extension:

![image](https://user-images.githubusercontent.com/786691/186115589-e7385408-d4f9-426f-b435-0864cc556ffc.png)

As you can see, it doesn't show nested items as complete even when they are marked with `[x]`

**Comment by jotaen** [comment]
Hey, thanks for sharing your idea. You are onto something with this, and there is already [an ongoing discussion about nested sub-items](https://github.com/jotaen/xit/discussions/2) – unfortunately it’s on hold right now. I think the idea in itself is valid and useful, but I’m currently reluctant because it seems to be difficult to make this happen in tooling. It seems that mostly the editor’s syntax highlighting engines are somewhat limited. But there are also other corner cases and implications.

Before considering to add this to the spec, it would be important for me to see an experimental implementation of this feature, e.g. in a syntax highlighting plugin. That way, it would be possible to get a more realistic feeling for the bits and bobs of the functionality.

I hope you don’t mind if I close this issue in favour of the linked discussion, just to keep the topics organised.

**Comment by benknight** [comment]
Oh sorry, I only searched the issues, not the discussions before posting this. Thanks for your quick response.
